### ISSUE TITLE
Keeping Track Of Installed Packages

### ISSUE THREAD

**Issue by BlockBusterBPL** [BlockBusterBPL/datapackmanager#3]
The way that i want to keep track of installed files is using YAML data. In a worldsave you would have a file like this:
```yaml
meta:
  savename: "redstone"
  title: "Redstone Testing World"
packages:
  installed:
    - "dpm-core"
    - "mechanization"
    - "devtools"
```
I will have to find a way to get bash to output to these files using YQ.
